{
  "openapi": "3.1.0",
  "info": {
    "version": "1.0.1",
    "title": "WalletAPI",
    "description": "REST API Application",
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "API base URL"
    }
  ],
  "tags": [
    {
      "name": "Users",
      "description": "Authorization endpoints"
    },
    {
      "name": "Transactions",
      "description": "Transactions endpoints"
    },
    {
      "name": "Statistics",
      "description": "Statistics endpoints"
    }
  ],
  "paths": {
    "/api/users/register": {
      "post": {
        "tags": ["Users"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "success"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "201"
                    },
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "Success! New user added"
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "name": "John",
                        "email": "john@mail.com"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Invalid data"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Conflict",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "This email in use yet"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Try later please"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/users/login": {
      "post": {
        "tags": ["Users"],
        "summary": "User authentification",
        "parameters": [],
        "requestBody": {
          "description": "Authentification's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["email", "password"],
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "john@mail.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "john123"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "success"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "200"
                    },
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "Welcome, John!"
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "token": "62e42ea67d8857b38579497dtyjgfthd658",
                        "user": {
                          "name": "John",
                          "email": "john@mail.com",
                          "balance": 996470
                        },
                        "lastTransactions": [
                          {
                            "_id": "62e42ea67d8857b38579497d",
                            "amount": 500,
                            "isIncome": false,
                            "category": "Self",
                            "date": "22-09-2023",
                            "month": 9,
                            "year": 2023,
                            "comment": "Video games",
                            "balance": 995000,
                            "owner": "62e42ea67d8857",
                            "createdAt": "2023-09-22T09:09:04.419Z",
                            "updatedAt": "2023-09-22T09:09:04.419Z",
                            "categoryId": "2222244444"
                          },
                          {
                            "_id": "62e42ea67d8857b3857",
                            "amount": 500,
                            "isIncome": false,
                            "category": "Products",
                            "date": "22-09-2023",
                            "month": 9,
                            "year": 2023,
                            "comment": "Bread",
                            "balance": 995500,
                            "owner": "62e42ea67d8857b38579497d",
                            "createdAt": "2023-09-22T08:48:19.614Z",
                            "updatedAt": "2023-09-22T08:48:19.614Z",
                            "categoryId": "2222222222"
                          },
                          {
                            "_id": "62e42ea67d8857b3857949",
                            "amount": 123,
                            "isIncome": false,
                            "category": "Products",
                            "date": "22-09-2023",
                            "month": 9,
                            "year": 2023,
                            "comment": "Bread",
                            "balance": 996000,
                            "owner": "62e42ea67d8857b3",
                            "createdAt": "2023-09-22T08:34:26.038Z",
                            "updatedAt": "2023-09-22T08:34:26.038Z",
                            "categoryId": "2222222222"
                          },
                          {
                            "_id": "62e42ea67d8857b385794a",
                            "amount": 50,
                            "isIncome": false,
                            "category": "Products",
                            "date": "22-09-2023",
                            "month": 9,
                            "year": 2023,
                            "comment": "Tea",
                            "balance": 996123,
                            "owner": "62e42ea67d8857b38579497d",
                            "createdAt": "2023-09-22T08:34:06.912Z",
                            "updatedAt": "2023-09-22T08:34:06.912Z",
                            "categoryId": "2222222222"
                          },
                          {
                            "_id": "62e42ea67d8857b38579497dad45",
                            "amount": 99,
                            "isIncome": false,
                            "category": "Products",
                            "date": "22-09-2023",
                            "month": 9,
                            "year": 2023,
                            "comment": "Food",
                            "balance": 996173,
                            "owner": "62e42ea67d8857b38579497d67456",
                            "createdAt": "2023-09-22T08:33:48.108Z",
                            "updatedAt": "2023-09-22T08:33:48.108Z",
                            "categoryId": "2222222222"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Invalid data"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Try later please"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/users/logout": {
      "get": {
        "tags": ["Users"],
        "summary": "User logout",
        "parameters": [
          {
            "in": "header",
            "required": true,
            "name": "bearerAuth",
            "description": "User's token",
            "schema": { "type": "string" }
          }
        ],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "success"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "200"
                    },
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "Success! User logout"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Please relogin and try again"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Try later please"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/transactions/": {
      "post": {
        "tags": ["Transactions"],
        "summary": "Add user's transaction",
        "parameters": [
          {
            "in": "header",
            "required": true,
            "name": "bearerAuth",
            "description": "User's token",
            "schema": { "type": "string" }
          }
        ],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "description": "Transaction's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Transaction"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "Success"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "201"
                    },
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "New transaction added."
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "transaction": {
                        "date": "28-09-2023",
                        "income": false,
                        "category": "Products",
                        "comment": "Food",
                        "sum": 500,
                        "owner": "ObjectId"
                      },
                      "balance": 2000
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Invalid data"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "Unauthorized"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "401"
                    },
                    "message": {
                      "type": "string",
                      "example": "Please relogin and try again"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "Not Found"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "404"
                    },
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Try later please"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Transactions"],
        "summary": "Get user transactions",
        "parameters": [
          {
            "in": "header",
            "required": true,
            "name": "bearerAuth",
            "description": "User's token",
            "schema": { "type": "string" }
          }
        ],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "Success"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "200"
                    },
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "Success! Transactions received."
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "result": [
                          {
                            "_id": "62e42ea67d8857b38579497d65452sdd",
                            "amount": 99,
                            "isIncome": false,
                            "category": "Products",
                            "categoryId": "",
                            "date": "09-22-2023",
                            "month": 9,
                            "year": 2023,
                            "comment": "Food",
                            "owner": "62e42ea67d8857b38579497d",
                            "createdAt": "2023-09-22T21:14:53.661Z",
                            "updatedAt": "2023-09-22T21:14:53.661Z"
                          },
                          {
                            "_id": "62e42ea67d8857b38579497dfty545",
                            "amount": 22,
                            "isIncome": false,
                            "category": "Kids",
                            "categoryId": "",
                            "date": "22-09-2023",
                            "month": 4,
                            "year": 2023,
                            "comment": "Cola",
                            "owner": "62e42ea67d8857b385",
                            "createdAt": "2023-09-22T20:36:11.830Z",
                            "updatedAt": "2023-09-22T20:36:11.830Z"
                          },
                          {
                            "_id": "62e42ea67d8857b38579497d",
                            "amount": 212,
                            "isIncome": false,
                            "category": "Kids",
                            "categoryId": "",
                            "date": "03-09-2023",
                            "month": 3,
                            "year": 2023,
                            "comment": "Cinema",
                            "owner": "asd62e42ea67d8857b38579497d",
                            "createdAt": "2023-09-22T20:36:34.760Z",
                            "updatedAt": "2023-09-22T20:35:54.682Z"
                          },
                          {
                            "_id": "jyty5462e42ea67d8857b38579497d",
                            "amount": 202,
                            "isIncome": false,
                            "category": "Car",
                            "categoryId": "",
                            "date": "04-09-2023",
                            "month": 4,
                            "year": 2023,
                            "comment": "LPG",
                            "owner": "62e42ea67d885",
                            "createdAt": "2023-09-22T20:35:54.682Z",
                            "updatedAt": "2023-09-22T20:35:54.682Z"
                          },
                          {
                            "_id": "62e42ea67d8857b38579497l",
                            "amount": 202,
                            "isIncome": false,
                            "category": "Car",
                            "categoryId": "",
                            "date": "04-09-2023",
                            "month": 4,
                            "year": 2023,
                            "comment": "Oil",
                            "owner": "62e42ea67d8857b3857949743",
                            "createdAt": "2023-09-22T20:35:54.682Z",
                            "updatedAt": "2023-09-22T20:35:54.682Z"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "Unauthorized"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "401"
                    },
                    "message": {
                      "type": "string",
                      "example": "Please relogin and try again"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Try later please"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/transactions/:transactionId": {
      "get": {
        "tags": ["Transactions"],
        "summary": "Get transaction",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "Success"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "200"
                    },
                    "message": {
                      "type": "string",
                      "example": "Success ! Transaction received"
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "data": {
                          "transaction": {
                            "date": "28.09.2023",
                            "income": "false",
                            "category": "car",
                            "comment": "change oil",
                            "sum": 250,
                            "owner": "ObjectId"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "Error"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "404"
                    },
                    "message": {
                      "type": "string",
                      "example": "Transaction Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Try later please"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": ["Transactions"],
        "summary": "Update Transaction",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "Success"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "200"
                    },
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "Transaction update."
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "data": {
                          "transaction": {
                            "date": "28.09.2023",
                            "income": "false",
                            "category": "car",
                            "comment": "change oil",
                            "sum": 250,
                            "owner": "ObjectId"
                          },
                          "balance": 2000
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "Not Found"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "200"
                    },
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Try later please"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Transactions"],
        "summary": "Delete transaction",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "Success"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "200"
                    },
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "Transaction deleted."
                    },
                    "data": {
                      "transaction": {
                        "date": "28.09.2023",
                        "income": "false",
                        "category": "car",
                        "comment": "change oil",
                        "sum": 250,
                        "owner": "ObjectId"
                      },
                      "balance": 2000
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "Not Found"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "404"
                    },
                    "message": {
                      "type": "string",
                      "example": "Transaction Not Found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Try later please"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/statistics": {
      "get": {
        "tags": ["Statistics"],
        "summary": "Get user's statistics",
        "parameters": [
          {
            "in": "query",
            "required": true,
            "name": "month",
            "description": "Number of month to filter.",
            "schema": { "type": "string" }
          },
          {
            "in": "query",
            "required": true,
            "name": "year",
            "description": "Number of year to filter.",
            "schema": { "type": "string" }
          },
          {
            "in": "header",
            "required": true,
            "name": "bearerAuth",
            "description": "User's token",
            "schema": { "type": "string" }
          }
        ],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "Success"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "200"
                    },
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "Success! Statistics received."
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "data": {
                          "result": [
                            {
                              "Products": 3000
                            },
                            {
                              "Car": 12000
                            }
                          ],
                          "expense": 15000,
                          "income": 0
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "Unauthorized"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "401"
                    },
                    "message": {
                      "type": "string",
                      "example": "Please relogin and try again"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "Not Found"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "404"
                    },
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Try later please"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "_id": {
            "type": "string",
            "description": "User's id",
            "example": "62e42ea67d8857b38579497d"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "example": "john@mail.com"
          },
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "John"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "$2b$10$BB6rC4v06a7HxUp3ZWKGQmLJqokfsI55/r2XO9o5bvQlQZEXu"
          },
          "token": {
            "type": "string",
            "description": "User's token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5IkpXVCJ9.eyJpZCI6IjYyZTQyZWE2N2Q4ODU3YjM4NTc5NDk3ZCIsImlhdCI6MTY1OTEyNjg0NSw"
          },
          "balance": {
            "type": "number",
            "description": "User's balance",
            "example": 9890
          }
        }
      },
      "Transaction": {
        "type": "object",
        "required": ["date", "income", "sum"],
        "properties": {
          "_id": {
            "type": "string",
            "description": "Transaction's id",
            "example": "62e44dcd1f01ddfdec6003"
          },
          "income": {
            "type": "boolean",
            "description": "Transaction's bool",
            "example": "false"
          },
          "category": {
            "type": "string",
            "description": "Transaction's category",
            "example": "Products"
          },
          "comment": {
            "type": "string",
            "description": "Transaction's comment",
            "example": "Salt"
          },
          "sum": {
            "type": "number",
            "description": "User's balance after operation",
            "example": 3500
          },
          "owner": {
            "type": "string",
            "description": "Transaction's owner",
            "example": "62e42ea67d8857b38579497d"
          },
          "date": {
            "type": "string",
            "description": "Transaction's date",
            "example": "2023-09-28"
          },
          "createdAt": {
            "type": "string",
            "description": "Transaction's create date",
            "example": "2023-07-29T21:14:53.661Z"
          },
          "updatedAt": {
            "type": "string",
            "description": "Transaction's update date",
            "example": "2023-07-29T21:14:53.661Z"
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "Enter JWT Bearer token"
      }
    }
  }
}
